---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: detect-private-key
      - id: forbid-submodules
      - id: mixed-line-ending
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
      - id: shellcheck
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.30.0
    hooks:
      - id: yamllint
        args: [--strict, --config-file=.yamllint.yml]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args:
          - --config=pyproject.toml
          - --check
          - --target-version=py310
  - repo: https://github.com/pycqa/pylint
    rev: v3.0.1
    hooks:
      - id: pylint
        args: [
          "--rcfile=pylintrc"
        ]
  - repo: https://github.com/python-poetry/poetry
    rev: '1.4.0'
    hooks:
      - id: poetry-export
        name: poetry export prod depedencies
        args: [
          "-f", "requirements.txt",
          "-o", "requirements.txt",
          "--without-hashes"
        ]
      - id: poetry-export
        name: poetry export dev depedencies
        args: [
          "-f", "requirements.txt",
          "-o", "requirements-dev.txt",
          "--only", "dev",
          "--without-hashes"
        ]
...
